### ISSUE TITLE
Assignments Updates

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-06-18/Sung_M#1]
Please push your latest assignments. Also, continue submitting via the platform (github links work) as well.

**Comment by semoon07** [comment]
done and done.

**Comment by dojo-json** [comment]
Thanks for updating your assignments.

I recommend closing this issue automatically with your next push. Check out the documentation for closing issues with keywords: https://help.github.com/articles/closing-issues-using-keywords/

TLDR: Create a commit message that contains something like `closes #1`. Github will detect the keyword and close the issue.

**Comment by dojo-json** [comment]
Push your latest assignments please.
